1.2.1e
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, 
значение элемента с индексом (3,1) и второй столбец. Индексация 
начинается с нуля.

In [1]:
#1.2.1

import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


1.2.2e
1.  Создать вектор (одномерный массив) размера 10, заполненный 
нулями. 
2.  Создать вектор размера 10, заполненный единицами. 
3.  Создать вектор размера 10, заполненный заданным числом. 
4.  Создать вектор со значениями от 10 до 19.

In [2]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(f'{a}\n{b}\n{c}\n{d}')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[10 11 12 13 14 15 16 17 18 19]


1.2.3e
Создать массив 10x10 со случайными значениями, найти минимум, 
максимум и среднее значение.

In [3]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.002875971587383841 0.9999131503633695 0.5302639137332521


1.2.4e
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице 
местами.

In [4]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


1.2.5e
Выяснить результат следующих выражений: 
1. 0 * np.nan 
2. np.nan == np.nan 
3. np.inf > np.nan 
4. np.nan - np.nan 
5. 0.3 == 3 * 0.1

In [5]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


1.2.6e
Отсортировать массив.

In [6]:
arr = np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


1.3.1
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и 
единицами.

In [7]:
a = np.ones((8,8), dtype = int)
a[::2, ::2] = 0
a[1::2, 1::2] = 0
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1.3.2
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания 
необходимо использовать функцию arrange.

In [8]:
a = np.zeros((5,5), dtype=int)
a += range(5)
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3
Создать массив 3x3x3 со случайными значениями. 

In [9]:
a = np.random.random((3,3,3))
print(a)

[[[0.69258608 0.49045587 0.14197894]
  [0.97670487 0.48354677 0.83843518]
  [0.99167799 0.04130922 0.93924772]]

 [[0.52241422 0.54033375 0.20966662]
  [0.59466789 0.89197854 0.88986057]
  [0.51846646 0.84475683 0.6101096 ]]

 [[0.90804876 0.41691019 0.69587593]
  [0.10186798 0.1223203  0.81916949]
  [0.23502527 0.37724747 0.72418012]]]


1.3.4
Создать матрицу с 0 внутри, и 1 на границах. 

In [10]:
a = np.ones((10,10), dtype=int)
a[1:-1, 1:-1] = 0
print(a)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


1.3.5
Создайте массив и отсортируйте его по убыванию.

In [11]:
a = np.array([3,5,2,4,7,8,2,3,4,7,0])
a = np.sort(a)[::-1]
print(a)

[8 7 7 5 4 4 3 3 2 2 0]


1.3.6
Создайте матрицу, выведите ее форму, размер и размерность. 

In [61]:
a = np.zeros((5,5,5,5,5), dtype=int)
print('матрица', ('квадратная', 'прямоугольная')[len(set(np.shape(a))) != 1])
print('формы', np.shape(a))
print('размера', a.size)
print('размерностью', len(np.shape(a)))

матрица квадратная
формы (5, 5, 5, 5, 5)
размера 3125
размерностью 5


2.2.1
Создать  Series  из  списка  Python,  словаря  Python,  и  массива  Numpy 
(установить буквенные метки для последнего). 

In [13]:
import pandas as pd
import numpy as np

lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])
s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


2.2.2
Дано два Series. Напечатать их первые элементы и все элементы после 
третьего (во втором фрейме). 

In [14]:
s1 = pd.Series([1,2,3,4,5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


2.2.3
Создайте новый фрейм данных.

In [15]:
dataFrame = pd.DataFrame()
dataFrame['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataFrame['Возраст'] = [38, 25]
dataFrame['Водитель'] = [True, False]
dataFrame

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

Загрузите фрейм данных по ссылке: 
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [37]:
#url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
dataFrame = pd.read_csv(url)
dataFrame.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

2.2.5
Пронализировать характеристики фрейма данных. 

In [38]:
dataFrame.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [39]:
dataFrame.tail(3)

PassengerId  Survived  Pclass                                      Name  \
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [40]:
dataFrame.shape

(891, 12)

In [41]:
dataFrame.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

2.2.6
Выберите индивидуальные данные или срезы фрейма данных. 

In [42]:
#dataFrame.iloc[1:4, 0:3:2]
dataFrame.loc[:, ("Name", "Age")]

Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

2.2.7
Требуется  отобрать  строки  фрейма  данных  на  основе  некоторого 
условия. Необходимо сформировать новый фрейм данных из пассажиров 
первого класса. 

In [46]:
dataFrame[dataFrame['Pclass'] == 1][dataFrame['Age'] == 2]#.head(2)


C:\Users\Sergey\AppData\Local\Temp\ipykernel_20784\2363320030.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  dataFrame[dataFrame['Pclass'] == 1][dataFrame['Age'] == 2]#.head(2)


PassengerId  Survived  Pclass                          Name     Sex  Age  \
297          298         0       1  Allison, Miss. Helen Loraine  female  2.0   

     SibSp  Parch  Ticket    Fare    Cabin Embarked  
297      1      2  113781  151.55  C22 C26        S

2.3.1
Найдитн евклидово расстояние между двумя Series (точками) a и b, не 
используя встроенную формулу.

In [47]:
a = pd.Series((1,2))
b = pd.Series((3,5))

s = 0
for i in range(len(a)):
    print(a[i])
    s += (b[i] - a[i])**2
s = np.sqrt(s)
print('расстояние между a и b =', round(s, 3))

1
2
расстояние между a и b = 3.606


2.3.2
Найдите в Интернете ссылку на любой csv файл и сформируйте из него 
фрейм данных (например, коллекцию фреймов данных можно найти 
здесь: https://github.com/akmand/datasets). 

In [48]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/donner_party.csv'
dataFrame = pd.read_csv(url)
dataFrame.head(5)

age  gender    status
0   23  female  survived
1   40    male      died
2   40  female      died
3   30  female  survived
4   28  female  survived

2.3.3
Проделайте с получившемся из предыдущего задания фреймом данных 
те же действия, что и в примерах 2.2.5-2.2.7.

In [49]:
dataFrame.tail(3)

age  gender    status
42   23  female      died
43   24  female  survived
44   25    male      died

In [50]:
dataFrame.shape

(45, 3)

In [51]:
dataFrame.describe()

age
count  45.000000
mean   31.800000
std    12.511086
min    15.000000
25%    24.000000
50%    28.000000
75%    40.000000
max    65.000000

In [52]:
dataFrame.iloc[3:6]

age  gender    status
3   30  female  survived
4   28  female  survived
5   40  female  survived

In [53]:
dataFrame[dataFrame['status'] == 'died'].head(4)

age  gender status
1    40    male   died
2    40  female   died
11   28  female   died
14   22    male   died

3.2.1
Прошкалируйте числовой признак в диапазон между двумя значениями.

In [54]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minimaxScale = preprocessing.MinMaxScaler(feature_range=(0, 1))
scaledFeature = minimaxScale.fit_transform(feature)
scaledFeature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

3.2.2
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное 
отклонение 1. 

In [55]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
print(standardized)
print('Среднее:', round(standardized.mean()))
print('Стандартное отклонение:', standardized.std())

[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
Среднее: 0
Стандартное отклонение: 1.0


3.2.3
Дан фрейм данных  
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21], 
                           'B':[103.02,107.26,110.35,114.23,114.68], 
                           'C':['big','small','big','small','small']}) 
Необходимо масштабировать его числовые столбцы

In [56]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A','B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

3.3.2
Загрузить фрейм данных по ссылке: 
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. 
Необходимо выполнить нормализацию первого числового признака 
(sepal_length_cm) с использованием минимаксного преобразования, а 
второго (sepal_width_cm) с задействованием z-масштабирования.

In [57]:
import pandas as pd
from sklearn import preprocessing 
from sklearn.preprocessing import MinMaxScaler


url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataFrame = pd.read_csv(url)

minMaxScaler = MinMaxScaler()
dataFrame[['sepal_length_cm']] = minMaxScaler.fit_transform(dataFrame[['sepal_length_cm']])

standardScaler = preprocessing.StandardScaler()
dataFrame[['sepal_width_cm']] = standardScaler.fit_transform(dataFrame[['sepal_width_cm']])
dataFrame

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]